### ISSUE TITLE
Fix coverage upload

### ISSUE THREAD

**Issue by Kludex** [Kludex/no-optional#4]

**Comment by webknjaz** [comment]
https://hynek.me/articles/ditch-codecov-python/ I suppose?

**Comment by Kludex** [comment]
It can be. 👍

**Comment by webknjaz** [comment]
@Kludex looks like you need to register here: https://app.codecov.io/gh/Kludex/no-optional — so that it's possible to send coverage there too.

**Comment by Kludex** [comment]
I've added the `CODECOV_TOKEN`.

This needs to be in place:
```yml
- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v3
  env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```
